front:
  build: .
  ports:
    - "80:80"
    - "443:443"
    - "3000:3000"
  links:
    - mysql:mysql
    - mongo:mongo
    - redis:redis
  volumes:
    - ./www:/var/www
    - ./sites:/etc/nginx/conf.d
    - ./logs:/var/log/supervisor

mysql:
  image: mysql
  ports:
    - "3306:3306"
  environment:
    MYSQL_ROOT_PASSWORD: p@ssword!

mongo:
  image: mongo
  ports:
    - "27017:27017"


redis:
  image: redis
  ports:
    - "6379:6379"
