front:
  image: worker01:5000/knowhow_front
  build: .
  ports:
    - "80:80"
    - "443:443"
    - "3000:3000"
  links:
    - mysql:mysql
    - mongo:mongo
    - redis:redis
  environment:
    - ENVIRONMENT=${ENVIRONMENT}
  volumes:
    - ./www:/var/www
    - ./sites:/etc/nginx/conf.d
    - ./logs:/logs

mysql:
  image: mysql
  ports:
    - "3306:3306"
  environment:
    MYSQL_ROOT_USER: root
    MYSQL_ROOT_PASSWORD: p@ssword!
    MYSQL_DATABASE: knowhow
    MYSQL_USER: admin
    MYSQL_PASSWORD: p@ssword!


mongo:
  image: mongo
  ports:
    - "27017:27017"


redis:
  image: redis
  ports:
    - "6379:6379"
